---
language: "python"
services:
  - "docker"
python:
  - 3.7

before_script:
  - "pip install invoke toml"
  - "invoke build-image -p $TRAVIS_PYTHON_VERSION"

script:
  - "invoke tests -p $TRAVIS_PYTHON_VERSION"
