---
# Add additional stages in the order of execution here, and then under the job:include: key
dist: "focal"  # Ubuntu 20.04
stages:
  - name: "lint"
  - name: "test"
  - name: "integration"
  - name: "deploy-github"
    if: "tag IS present"
  - name: "deploy-pypi"
    if: "tag IS present"

language: "python"
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

services:
  - "docker"

# Poetry 1.1.0 added parallel installation as an option;
# unfortunately it seems to have some issues with installing/updating "requests" and "certifi"
# while simultaneously attempting to *use* those packages to install other packages.
# For now we disable it with "poetry config installer.parallel false"

# before_install, Script & before_script for test stage
before_install: >
  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1

before_script:
  - "pip install invoke"
  - "invoke build-image --nocache"
script:
  - "invoke pytest"

jobs:
  include:
    - stage: "lint"
      env:
        - "INVOKE_LOCAL=True"
      before_script:
        - "pip install invoke poetry toml"
        - "poetry config virtualenvs.create false"
        - "poetry config installer.parallel false"
        - "poetry install --no-interaction --no-ansi --no-root"
      script:
        - "invoke black"
        - "invoke bandit"
        - "invoke pydocstyle"
        - "invoke flake8"
        - "invoke yamllint"
        - "invoke pylint"
      python: 3.7

    - stage: "integration"
      name: "Nautobot v1.0.1"
      before_install: >
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1
      before_script:
        - "pip install --upgrade pip wheel"
        - "pip install invoke toml poetry pynautobot ansible-base==2.11.1"
        - "ansible-galaxy collection install networktocode.nautobot"
        - "poetry config virtualenvs.create false"
        - "poetry config installer.parallel false"
        - "poetry install"
      script:
        - "invoke nautobot-integration-tests"
      after_script:
        - "cd /tmp && docker-compose logs"
      env: "NAUTOBOT_VERSION=1.0.1"
      python: 3.7

    - stage: "integration"
      name: "Netbox v2.10"
      before_install: >
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1
      before_script:
        - "pip install invoke toml poetry pynetbox ansible==2.10.7"
        - "ansible-galaxy collection install git+https://github.com/netbox-community/ansible_modules.git,v3.0.0"
        - "poetry config virtualenvs.create false"
        - "poetry config installer.parallel false"
        - "poetry install"
      script:
        - "invoke integration-tests"
      env: "NETBOX_VERSION=v2.10"
      python: 3.7

    - stage: "integration"
      name: "Netbox v2.9"
      before_install: >
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1
      before_script:
        - "pip install invoke toml poetry pynetbox ansible==2.10.7"
        - "ansible-galaxy collection install git+https://github.com/netbox-community/ansible_modules.git,v3.0.0"
        - "poetry config virtualenvs.create false"
        - "poetry config installer.parallel false"
        - "poetry install"
      script:
        - "invoke integration-tests"
      env: "NETBOX_VERSION=v2.9"
      python: 3.7

    - stage: "integration"
      name: "Netbox v2.8"
      before_install: >
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin || travis_terminate 1
      before_script:
        - "pip install invoke toml poetry pynetbox ansible==2.10.7"
        - "ansible-galaxy collection install git+https://github.com/netbox-community/ansible_modules.git,v3.0.0"
        - "poetry config virtualenvs.create false"
        - "poetry config installer.parallel false"
        - "poetry install"
      script:
        - "invoke integration-tests"
      env: "NETBOX_VERSION=v2.8"
      python: 3.7

    - stage: "deploy-github"
      before_script:
        - "pip install poetry"
      script:
        - "poetry version $TRAVIS_TAG"
        - "poetry build"
      deploy:
        provider: "releases"
        api_key: "$GITHUB_AUTH_TOKEN"
        file_glob: true
        file: "dist/*"
        skip_cleanup: true
        "on":
          all_branches: true

    - stage: "deploy-pypi"
      before_script:
        - "pip install poetry"
      script:
        - "poetry version $TRAVIS_TAG"
        - "poetry config pypi-token.pypi $PYPI_TOKEN"
        - "poetry publish --build"
