---
language: "python"
services:
  - "docker"
python:
  - 3.7

before_script:
  - "pip install invoke toml poetry ansible pynetbox"
  - "ansible-galaxy collection install netbox.netbox"
  - "poetry install"
  - "invoke build-image -p $TRAVIS_PYTHON_VERSION"

script:
  # TODO Update invoke to pass the version of python.
  - invoke tests
  - invoke integration-tests
