[main]
inventory_source = "nautobot"
import_ips = true 
import_prefixes = false
import_intf_status = false

# Vlans (name, vlan-id) can be imported from the configuration, from the CLI or both 
# - "config" will import the vlans just from the configuration
# - "cli" will import the vlans from the cli using the action `get_vlans`
# - "true" will import vlans from both cli and config
# - no or false will not import any vlans
# The association between interface and vlans will always be derived from the configuration.
import_vlans = "cli"         # Valid options are ["cli", "config", "no", true, false]

# Cabling can be imported from LLDP, CDP or the configuration (for some point to point links)
# - "lldp" or "cdp" will import the vlans from the cli using the action `get_neighbors`
# - "config" will import the neighbors from the configuration (for point to point links)
# - "true" will import neighbors from both cli and config 
# - no or false will not import any neighbors
import_cabling = "cdp"         # Valid options are ["lldp", "cdp", "config", "no", true, false]
excluded_platforms_cabling = ["cisco_asa"]

# Number of Nornir tasks to execute at the same tim
nbr_workers= 25

# Directory where the configuration can be find, organized in Batfish format
configs_directory = "configs"

# [netbox]
# address = "https://nautobot8"                   # Alternative Env Variable : NETBOX_ADDRESS
# token = "6fd167451be23bc5104bc07995fa9f4185c33d48"  # Alternative Env Variable : NETBOX_TOKEN
# verify_ssl = false                                   # Alternative Env Variable : NETBOX_VERIFY_SSL

# # Define a list of supported platform, 
# # if defined all devices without platform or with a different platforms will be removed from the inventory
# supported_platforms = [ "cisco_ios", "cisco_nxos" ]

# # Settings for applying diffsync flags to diffsync model objects, in order to alter 
# # the underlying sync behaviour. The model_flag is applied to any objects that have a 
# # tag assigned within model_flag_tags. Further details on model_flags can be found 
# # at: https://github.com/networktocode/diffsync/blob/269df51ce248beaef17d72374e96d19e6df95a13/diffsync/enum.py
# model_flag_tags = ["your_tag"]
# model_flag = 1 # flag enum int() representation

[batfish]
address = "dockerrunner"   # Alternative Env Variable : BATFISH_ADDRESS
network_name = "network-importer"
snapshot_name = "latest"
port_v1 = 9997
port_v2 = 9996
use_ssl = false

[network]
login = "cisco"          # Alternative Env Variable : NETWORK_DEVICE_LOGIN
password = "Cisco123!"       # Alternative Env Variable : NETWORK_DEVICE_PWD
enable = true               # Alternative Env Variable : NETWORK_DEVICE_ENABLE

# Connection parameters for Netmiko 
global_delay_factor = 5
banner_timeout = 15
conn_timeout = 5

# List of valid FQDN that can be found in the network,
# The FQDNs in this list will be automatically removed from all neighbors discovered from LLDP/CDP
fqdns = [ ]

[inventory]
# The default method is to use the primary IP defined in NetBox.
# As an alternative it's possible to use the name of the device and provide your own FQDN.
use_primary_ip = false # (default: true)
fqdn = "joshv.com"

# Optional filter to limit the scope of the inventory, takes a comma separated string of key value pair"
filter = "device=sw01" # ,site=YYY,status=active"    # Alternative Env Variable : INVENTORY_FILTER

# Configure what Inventory will be loaded bu the network importer.
inventory_class = "network_importer.inventory.NetboxInventory"

[nautobot]
address = "https://nautobot8:443"                   # Alternative Env Variable : NETBOX_ADDRESS
token = "6fd167451be23bc5104bc07995fa9f4185c33d48"  # Alternative Env Variable : NETBOX_TOKEN
verify_ssl = false                                   # Alternative Env Variable : NETBOX_VERIFY_SSL

# Define a list of supported platform, 
# if defined all devices without platform or with a different platforms will be removed from the inventory
supported_platforms = [ "cisco_ios", "cisco_nxos" ]

# Settings for applying diffsync flags to diffsync model objects, in order to alter 
# the underlying sync behaviour. The model_flag is applied to any objects that have a 
# tag assigned within model_flag_tags. Further details on model_flags can be found 
# at: https://github.com/networktocode/diffsync/blob/269df51ce248beaef17d72374e96d19e6df95a13/diffsync/enum.py
model_flag_tags = ["your_tag"]
model_flag = 1 # flag enum int() representation

[netbox]
address = "https://nautobot8"
token = "6fd167451be23bc5104bc07995fa9f4185c33d48"  # Alternative Env Variable : NETBOX_TOKEN
verify_ssl = false                                   # Alternative Env Variable : NETBOX_VERIFY_SSL

# Define a list of supported platform, 
# if defined all devices without platform or with a different platforms will be removed from the inventory
supported_platforms = [ "cisco_ios", "cisco_nxos" ]

# Settings for applying diffsync flags to diffsync model objects, in order to alter 
# the underlying sync behaviour. The model_flag is applied to any objects that have a 
# tag assigned within model_flag_tags. Further details on model_flags can be found 
# at: https://github.com/networktocode/diffsync/blob/269df51ce248beaef17d72374e96d19e6df95a13/diffsync/enum.py
