[tool.poetry]
name = "network-importer"
version = "2.0.0-dev"
description = "Network Importer tool to import an existing network into a Database / Source Of Truth"
authors = ["Damien Garros <dgarros@gmail.com>"]
license = "Apache-2.0"
packages = [
    { include = "network_importer" },
    { include = "dsync" },
]

[tool.poetry.dependencies]
python = "^3.7"
pynetbox = "^4.3"
jsonschema = {version = "^3.2.0" }
toml = {version = "^0.10.0" }
nornir = "^2.4"
termcolor = "^1.1"
click = "^7.1.1"
pydantic = "^1.6.1"
pybatfish = "^2020.8.11"
"genie.metaparser" = "^19.12"
genie = "^20.9"
pyats = "^20.9"
netmiko = "^3.3.2"
ntc-templates = "^1.6.0"
structlog = "^20.1.0"

[tool.poetry.dev-dependencies]
bandit = "^1.6"
pylint = "^2.4"
pyment = "^0.3"
pytest = "^5.4"
pdbpp = "^0.10.2"
requests_mock = "^1.7"
black = {version = "^19.10b0", allow-prereleases = true}

[tool.poetry.scripts]
network-importer = 'network_importer.cli:main'

[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
        /(
          \.git
        | \.tox
        | \.venv
        | env/
        | _build
        | build
        | dist
        )/
    '''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

