---
- name: "CREATE ALL OBJECTS REQUIRED FOR THE NETWORK IMPORTER IN NAUTOBOT"
  hosts: ["all"]
  gather_facts: false
  connection: "local"
  vars:
    device_roles: ["spine", "leaf", "router"]
    platforms:
      - {name: "junos", manufacturer: "juniper"}
      - {name: "iosxr", manufacturer: "cisco"}
      - {name: "ios", manufacturer: "cisco"}
      - {name: "nxos", manufacturer: "cisco"}
      - {name: "eos", manufacturer: "arista"}
    site_prefix: "ni_02"
    region: "ni_multi_site_02"
    sites: ["hou", "nyc", "sjc"]
    nautobot_address: "{{ lookup('env','NAUTOBOT_ADDRESS') }}"
    nautobottoken: "{{ lookup('env','NAUTOBOT_SUPERUSER_API_TOKEN') }}"

  tasks:
    - name: "01 CREATE REGION IN NAUTOBOT"
      networktocode.nautobot.region:
        url: "{{ nautobot_address }}"
        token: "{{ nautobot_token }}"
        data:
          name: "{{ region }}"
        state: "present"
      run_once: true
      tags: ["region"]

    - name: "05 CREATE MANUFACTURER IN NAUTOBOT"
      networktocode.nautobot.manufacturer:
        url: "{{ nautobot_address }}"
        token: "{{ nautobot_token }}"
        data:
          name: "{{ item.manufacturer }}"
        state: "present"
      loop: "{{ platforms }}"
      run_once: true
      tags: ["manufacturer", "device_type"]

    - name: "10 CREATE DEVICE TYPE IN NAUTOBOT"
      networktocode.nautobot.device_type:
        url: "{{ nautobot_address }}"
        token: "{{ nautobot_token }}"
        data:
          slug: "{{ item.name }}"
          model: "{{ item.name }}"
          manufacturer: "{{ item.manufacturer }}"
          part_number: "{{ item.name }}"
          u_height: 1
          is_full_depth: false
        state: "present"
      loop: "{{ platforms }}"
      run_once: true
      tags: ["device_type"]

    - name: "15 CREATE DEVICE ROLE IN NAUTOBOT"
      networktocode.nautobot.device_role:
        url: "{{ nautobot_address }}"
        token: "{{ nautobot_token }}"
        data:
          name: "{{ item }}"
          color: "0000FF"
        state: "present"
      loop: "{{ device_roles }}"
      run_once: true
      tags: ["device_role"]

    - name: "20 CREATE SITE IN NAUTOBOT"
      networktocode.nautobot.site:
        url: "{{ nautobot_address }}"
        token: "{{ nautobot_token }}"
        data:
          name: "{{ site_prefix}}_{{item }}"
          region: "{{ region }}"
        state: "present"
      loop: "{{ sites }}"
      run_once: true
      tags: ["device_site"]

    - name: "25 CREATE DEVICES IN NAUTOBOT"
      networktocode.nautobot.device:
        url: "{{ nautobot_address }}"
        token: "{{ nautobot_token }}"
        data:
          name: "{{ inventory_hostname }}"
          device_type: "{{ platform }}"
          device_role: "{{ role }}"
          site: "{{ site_prefix}}_{{site }}"
        state: "present"
      tags: ["device"]
